version: "3"
services:
  crossbar:
    build: ./router
    container_name: crossbar
    ports:
      - "80:80"
    # volumes:
    #    - type: volume
    #     source: react-build
    #     target: ./

  adjudicator:
    build: ./adjudicator
    links:
      - "crossbar"
    command: ["python", "invoke.py"]
  # game_gen:
  #   build: ./game_gen
  #   links:
  #     - "crossbar"
  #   command: ["python", "game_gen.py", "1", "6"]
  # react-build:
  #   build: ./web-ui
# volumes:
#   react-build:
