version: "3"

services:
  crossbar:
    build: ./router
    container_name: crossbar
    networks:
      - gateway
    ports:
      - "80:80"
    volumes:
      - webapp:/app/
  game_gen:
    build: ./adjudicator
    restart: on-failure
    networks:
      - gateway
  webapp:
    build: ./web-ui
    container_name: webapp
    tty: true
    volumes:
      - webapp:/app/

networks:
  gateway: {}

volumes:
  webapp:
