version: "3"

services:
  crossbar:
    build: ./router
    container_name: crossbar
    networks:
      - gateway
    ports:
      - "3000:3000"
    volumes:
      - webapp
  game_gen:
    build: ./adjudicator
    networks:
      - gateway
  webapp:
    build: ./web-ui
    container_name: webapp

networks:
  gateway: {}

volumes:
  webapp:
