version: "3"

services:
  crossbar:
    build: ./router
    container_name: crossbar
    networks:
      - gateway
    ports:
      - "80:80"
    volumes:
      - webapp
  adjudicator:
    build: ./adjudicator
    networks:
      - gateway
    command: ["python", "newAdjudicator.py"]
  webapp:
    build: ./web-ui
    container_name: webapp

networks:
  gateway: {}

volumes:
  webapp:
