version: "3"

services:
  crossbar:
    build: ./router
    container_name: crossbar
    networks:
      - gateway
    ports:
      - "80:80"
    volumes:
      - webapp:/app/
  game_gen:
    build: ./adjudicator
    restart: on-failure
    networks:
      - gateway
  webpages:
    build: ./webpages
    container_name: webpages
    tty: true
    volumes:
      - webapp:/app/
  db:
    image: mysql/mysql-server:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    networks:
      - gateway
    volumes:
      - ./monopoly.sql:/docker-entrypoint-initdb.d/monopoly.sql
    environment:
      MYSQL_ROOT_PASSWORD: root123

networks:
  gateway: {}

volumes:
  webapp:
