version: "3"
services:
  crossbar:
    build: ./router
    container_name: crossbar
    ports:
      - "80:80"
    # volumes:
    #    - type: volume
    #     source: react-build
    #     target: ./

  adjudicator:
    build: ./adjudicator
    links:
      - "crossbar"
    command: ["python", "adjudicator.py"]

  game_gen:
    build: ./game_gen
    links:
      - "crossbar"
  # react-build:
  #   build: ./web-ui
# volumes:
#   react-build:
