version: "3"
services:
  router:
    build: ./router
    container_name: crossbar
    ports:
      - "80:80"

  adjudicator:
    build: ./adjudicator
    links:
      - router

  game_gen:
    build: ./game_gen
    links:
      - router
