export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const SET_PROPS = "SET_PROPS";
export const SET_SELECTED_PROP_INDEX = "SET_SELECTED_PROP";
export const SET_OTHER_PLAYER = "SET_OTHER_PLAYER";
export const TOGGLE_PROPERTY_MODAL = "TOGGLE_PROPERTY_MODAL";
